### ISSUE TITLE
插件编译出错,求解决

### ISSUE THREAD

**Issue by flyshadowhan** [phinehasz/sonar-pmd-xml-plugin#3]
[ERROR] /sonar-pmd-xml-plugin-master/sonar-pmd-xml-plugin-master/sonar-p3c-pmd/src/main/java/org/sonar/plugins/pmd/PmdTemplate.java:[83,54] 找不到符号
[ERROR]   符号:   变量 SonarProperty
[ERROR]   位置: 类 org.sonar.plugins.pmd.PmdTemplate

**Comment by xsser** [comment]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.058 s
[INFO] Finished at: 2020-04-15T17:00:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/xxx/Downloads/代码扫描项目/sonar-pmd-xml-plugin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by xsser** [comment]
+1  我也是这个问题

**Comment by chimisu** [comment]
@phinehasz 是不是少了个文件呀？我也编译不过去。

**Comment by chimisu** [comment]
已解决，但是这个不支持7.x，建议去看https://github.com/rhinoceros/sonar-p3c-pmd/releases/tag/pmd-3.2.0-beta-with-p3c1.3.4-pmd6.10.0

**Comment by xsser** [comment]
> 已解决，但是这个不支持7.x，建议去看https://github.com/rhinoceros/sonar-p3c-pmd/releases/tag/pmd-3.2.0-beta-with-p3c1.3.4-pmd6.10.0

这个能支持xpath rules规则么 或者说是在sonar7.9 LTS版上能正常用吗

**Comment by phinehasz** [comment]
> 已解决，但是这个不支持7.x，建议去看https://github.com/rhinoceros/sonar-p3c-pmd/releases/tag/pmd-3.2.0-beta-with-p3c1.3.4-pmd6.10.0

应该是少了类，这个不影响。7.x版本支持的，我公司用的都是7.2版本。

**Comment by phinehasz** [comment]
> > 已解决，但是这个不支持7.x，建议去看https://github.com/rhinoceros/sonar-p3c-pmd/releases/tag/pmd-3.2.0-beta-with-p3c1.3.4-pmd6.10.0
> 
> 这个能支持xpath rules规则么 或者说是在sonar7.9 LTS版上能正常用吗

xpath rule是pmd里的吧？不过是父类为XpathRule的一类规则，都支持的。
